# Generated by Django 4.2 on 2025-01-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_lanchonete', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id_payment_method',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='id_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='id_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='id_product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
