# Generated by Django 4.2 on 2025-01-06 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_admin_user_alter_client_user'),
        ('minha_lanchonete', '0002_rename_id_product_drink_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='minha_lanchonete.product'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='minha_lanchonete.product'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('client', 'number')},
        ),
    ]
